GAME_STATES = {
    "INTRO": 'INTRO',
    "HOME": 'HOME',
    "GAME": 'GAME',
    "GAME_OVER": 'GAME_OVER',
    "FINISH": 'FINISH',
}

MOVE_ACTION_X = {
    "LEFT": 'LEFT',
    "RIGHT": 'RIGHT',
    "STOP": 'STOP',
    "STOP_LEFT": 'STOP_LEFT',
    "STOP_RIGHT": 'STOP_RIGHT'
}
MOVE_ACTION_Y = {
    "TOP": 'TOP',
    "BOTTOM": 'BOTTOM',
    "STOP": 'STOP',
    "STOP_TOP": 'STOP_TOP',
    "STOP_BOTTOM": 'STOP_BOTTOM'
}

# ICI on definis la config du jeu
ALIENS_ANIMATION_TIME = 1.000
ALIENS_SHOOT_TIME = 1.000
ALIENS_SPEED_MOVE = 10
ALIENS_MAX_RIGHT = 50

FPS = 60

PLAYER_BULLET_SPEED = 5
ALIEN_BULLET_SPEED = 2

PLAYER_SPEED_MOVE = 3

PLAYER_LIFES = 3

ALIEN_LIFES = 1
